from __future__ import annotations

from collections.abc import Iterable, Mapping
from datetime import datetime
from decimal import Decimal
from types import MappingProxyType

from app.ingestion.contracts import (
    SourceConfig,
    SourceFormat,
    SourceMode,
    SourcePolicyMetadata,
)


POLICY_AUDIT_CHECKED_AT = datetime.fromisoformat("2026-06-27T17:45:00+05:00")
DEFAULT_FORBIDDEN_PATHS = (
    "/account",
    "/admin",
    "/appointment",
    "/booking",
    "/cabinet",
    "/cart",
    "/feedback",
    "/login",
    "/order",
    "/patient",
    "/payment",
    "/results",
    "/search",
)

EXPECTED_POLICY_SOURCE_IDS = frozenset(
    {
        "kdl_olymp",
        "invitro_kz",
        "invivo_kz",
        "gemotest_kz",
        "103_kz",
        "helix_kz",
        "doq_kz",
        "olymp_divera",
        "medel_kz",
        "aksai_clinic",
        "mck_kz",
        "city_clinic_document",
        "bmcudp",
        "umc",
        "astana_clinic",
        "gp5_astana",
        "gp4_astana",
        "gp6_astana",
        "almaty_cgkb",
        "sema_hospital",
        "medical_park",
        "lordoctor",
        "sunkar_premium",
        "onclinic_astana",
        "genom_eko",
        "duet_clinic",
        "mrt_lider",
        "magnesia",
        "snh",
        "tonus_med",
        "aktobe_mc",
        "qmu_clinics",
        "gpk_hippokrat",
        "medelement",
        "2gis_enrichment",
        "google_places_enrichment",
        "alataulab_kz",
        "onclinic_kz",
    }
)


class SourceExecutionBlockedError(RuntimeError):
    pass


class SourceRegistry:
    def __init__(self, configs: Iterable[SourceConfig]) -> None:
        indexed: dict[str, SourceConfig] = {}
        for config in configs:
            if config.source_id in indexed:
                raise ValueError(f"Duplicate source_id: {config.source_id}")
            indexed[config.source_id] = config
        self._configs: Mapping[str, SourceConfig] = MappingProxyType(indexed)
        self._source_ids = tuple(sorted(indexed))

    @property
    def configs(self) -> Mapping[str, SourceConfig]:
        return self._configs

    @property
    def source_ids(self) -> tuple[str, ...]:
        return self._source_ids

    def get(self, source_id: str) -> SourceConfig:
        try:
            return self._configs[source_id]
        except KeyError as exc:
            raise KeyError(f"Unknown source_id: {source_id}") from exc

    def require_live(self, source_id: str) -> SourceConfig:
        config = self.get(source_id)
        if config.mode is not SourceMode.LIVE or not config.enabled:
            raise SourceExecutionBlockedError(
                f"Source {source_id} is gated as {config.mode.value} and cannot execute live"
            )
        return config


def _policy(
    evidence_url: str,
    notes: str,
    *,
    robots_url: str | None = None,
    terms_review_status: str = "reviewed_no_reuse_grant",
) -> SourcePolicyMetadata:
    return SourcePolicyMetadata(
        robots_url=robots_url,
        checked_at=POLICY_AUDIT_CHECKED_AT,
        terms_review_status=terms_review_status,
        evidence_urls=(evidence_url,),
        notes=notes,
    )


def _source(
    *,
    source_id: str,
    display_name: str,
    source_type: str,
    mode: SourceMode,
    priority: str,
    formats: tuple[SourceFormat, ...],
    evidence_url: str,
    notes: str,
    allowed_hosts: tuple[str, ...] = (),
    allowed_paths: tuple[str, ...] = (),
    forbidden_paths: tuple[str, ...] = DEFAULT_FORBIDDEN_PATHS,
    start_urls: tuple[str, ...] = (),
    cities: tuple[str, ...] = (),
    delay: int = 10,
    pages: int = 1,
    max_bytes: int = 10_000_000,
    robots_url: str | None = None,
    enabled: bool = False,
) -> SourceConfig:
    return SourceConfig(
        source_id=source_id,
        display_name=display_name,
        source_type=source_type,
        mode=mode,
        priority=priority,
        formats=formats,
        allowed_hosts=allowed_hosts,
        allowed_path_prefixes=allowed_paths,
        forbidden_path_prefixes=forbidden_paths,
        start_urls=start_urls,
        city_scope=cities,
        minimum_delay_seconds=Decimal(delay),
        max_concurrency=1,
        max_pages_per_run=pages,
        max_document_bytes=max_bytes,
        adapter_version="0.1.0",
        policy=_policy(evidence_url, notes, robots_url=robots_url),
        enabled=enabled,
        adapter_module=None,
    )


SOURCE_CONFIGS = (
    _source(
        source_id="kdl_olymp",
        display_name="КДЛ ОЛИМП",
        source_type="laboratory",
        mode=SourceMode.LIVE,
        priority="P0",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("www.kdlolymp.kz", "kdlolymp.kz"),
        allowed_paths=("/pricelist",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/media", "/docs"),
        start_urls=("https://www.kdlolymp.kz/pricelist/almaty",),
        cities=("Алматы",),
        pages=20,
        evidence_url="https://www.kdlolymp.kz/pricelist/almaty",
        robots_url="https://www.kdlolymp.kz/robots.txt",
        notes="Only explicitly registered city price pages are eligible.",
        enabled=True,
    ),
    _source(
        source_id="invitro_kz",
        display_name="INVITRO Kazakhstan",
        source_type="laboratory",
        mode=SourceMode.PERMISSION_REQUIRED,
        priority="P0",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("invitro.kz",),
        evidence_url="https://invitro.kz/analizes/for-doctors/konaev/",
        robots_url="https://invitro.kz/robots.txt",
        notes="Written permission is required before automated collection.",
    ),
    _source(
        source_id="invivo_kz",
        display_name="INVIVO Kazakhstan",
        source_type="laboratory",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("invivo.kz",),
        evidence_url="https://invivo.kz/",
        notes="Identity, policy, and price URLs remain unconfirmed.",
    ),
    _source(
        source_id="gemotest_kz",
        display_name="Гемотест Казахстан",
        source_type="laboratory",
        mode=SourceMode.LIVE,
        priority="P0",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("gemotest.kz",),
        allowed_paths=("/catalog",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/corp", "/doctors"),
        start_urls=("https://gemotest.kz/catalog/",),
        pages=40,
        evidence_url="https://gemotest.kz/catalog/",
        robots_url="https://gemotest.kz/robots.txt",
        notes="Clean catalog paths only; city expansion must be explicit.",
        enabled=True,
    ),
    _source(
        source_id="103_kz",
        display_name="103.kz",
        source_type="aggregator",
        mode=SourceMode.PERMISSION_REQUIRED,
        priority="P0",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("www.103.kz",),
        evidence_url="https://www.103.kz/",
        robots_url="https://www.103.kz/robots.txt",
        notes="Aggregator content requires written reuse permission.",
        delay=20,
    ),
    _source(
        source_id="helix_kz",
        display_name="Helix Kazakhstan",
        source_type="laboratory",
        mode=SourceMode.MANUAL_IMPORT_ONLY,
        priority="P2",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("helix-lab.kz",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/catalog", "/test", "/doctors"),
        evidence_url="https://helix-lab.kz/",
        robots_url="https://helix-lab.kz/robots.txt",
        notes="Robots disallows catalog and test paths.",
    ),
    _source(
        source_id="doq_kz",
        display_name="DOQ.kz",
        source_type="aggregator",
        mode=SourceMode.SCAFFOLD,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("doq.kz",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/appointments",),
        evidence_url="https://doq.kz/",
        robots_url="https://doq.kz/robots.txt",
        notes="Stable public price coverage and reuse terms remain unconfirmed.",
        delay=15,
    ),
    _source(
        source_id="medelement",
        display_name="MedElement",
        source_type="aggregator",
        mode=SourceMode.PERMISSION_REQUIRED,
        priority="P2",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("medelement.com",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/api",),
        evidence_url="https://medelement.com/",
        robots_url="https://medelement.com/robots.txt",
        notes="Platform and third-party document rights require permission.",
    ),
    _source(
        source_id="olymp_divera",
        display_name="Olymp / DiVera",
        source_type="private_clinic",
        mode=SourceMode.MANUAL_IMPORT_ONLY,
        priority="P2",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("olymp.kz",),
        evidence_url="https://olymp.kz/",
        notes="Official identity and price ownership are unverified.",
    ),
    _source(
        source_id="medel_kz",
        display_name="MEDЭЛ",
        source_type="private_clinic",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("medel.kz",),
        evidence_url="https://medel.kz/",
        notes="Official identity and current price source are unconfirmed.",
    ),
    _source(
        source_id="aksai_clinic",
        display_name="Aksai Clinic",
        source_type="private_clinic",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("aksai-clinic.kz",),
        evidence_url="https://aksai-clinic.kz/",
        notes="Public price evidence remains unconfirmed.",
    ),
    _source(
        source_id="mck_kz",
        display_name="MCK",
        source_type="private_clinic",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("mck.kz",),
        evidence_url="https://mck.kz/",
        notes="Entity ownership and public price pages remain ambiguous.",
    ),
    _source(
        source_id="city_clinic_document",
        display_name="Reviewed city or regional clinic document",
        source_type="generic_document",
        mode=SourceMode.MANUAL_IMPORT_ONLY,
        priority="P1",
        formats=(
            SourceFormat.HTML,
            SourceFormat.PDF,
            SourceFormat.DOCX,
            SourceFormat.XLS,
            SourceFormat.XLSX,
        ),
        evidence_url="https://egov.kz/",
        notes="Each exact clinic document requires a separately reviewed mapping profile.",
        max_bytes=25_000_000,
    ),
    _source(
        source_id="bmcudp",
        display_name="Больница Медицинского центра УДП РК",
        source_type="state_clinic",
        mode=SourceMode.LIVE,
        priority="P0",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("bmcudp.kz", "www.bmcudp.kz"),
        allowed_paths=("/ru/services",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/bitrix",),
        start_urls=("https://bmcudp.kz/ru/services/",),
        cities=("Астана",),
        pages=30,
        evidence_url="https://bmcudp.kz/ru/services/",
        robots_url="https://bmcudp.kz/robots.txt",
        notes="Only Kazakhstan-citizen tariff pages may be registered.",
        enabled=True,
    ),
    _source(
        source_id="umc",
        display_name="University Medical Center",
        source_type="state_clinic",
        mode=SourceMode.MANUAL_IMPORT_ONLY,
        priority="P1",
        formats=(SourceFormat.PDF,),
        allowed_hosts=("umc.org.kz",),
        evidence_url="https://umc.org.kz/prejskurant-na-med-uslugi-kf-umc-3/",
        notes="Only a reviewed current medical PDF checksum may be imported.",
        max_bytes=25_000_000,
    ),
    _source(
        source_id="astana_clinic",
        display_name="Astana Clinic",
        source_type="state_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("www.astanaclinic.kz", "astanaclinic.kz"),
        allowed_paths=("/index.php/ru",),
        start_urls=("https://www.astanaclinic.kz/index.php/ru/30-prejskurant",),
        cities=("Астана",),
        pages=30,
        evidence_url="https://www.astanaclinic.kz/index.php/ru/30-prejskurant",
        robots_url="https://astanaclinic.kz/robots.txt",
        notes="Registered department pages only; select the Kazakhstan tariff column.",
        enabled=True,
    ),
    _source(
        source_id="gp5_astana",
        display_name="Городская поликлиника №5 Астана",
        source_type="state_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("gp5-astana.kz",),
        allowed_paths=("/ru/poliklinika/platnye-uslugi-i-tseny",),
        start_urls=("https://gp5-astana.kz/ru/poliklinika/platnye-uslugi-i-tseny",),
        cities=("Астана",),
        delay=15,
        evidence_url="https://gp5-astana.kz/ru/poliklinika/platnye-uslugi-i-tseny",
        robots_url="https://gp5-astana.kz/robots.txt",
        notes="One explicit public paid-services page per run.",
        enabled=True,
    ),
    _source(
        source_id="gp4_astana",
        display_name="Городская поликлиника №4 Астана",
        source_type="state_clinic",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("emhana-gp4.kz",),
        evidence_url="https://emhana-gp4.kz/",
        robots_url="https://emhana-gp4.kz/robots.txt",
        notes="Current public price URL remains unconfirmed.",
    ),
    _source(
        source_id="gp6_astana",
        display_name="Городская поликлиника №6 Астана",
        source_type="state_clinic",
        mode=SourceMode.MANUAL_IMPORT_ONLY,
        priority="P1",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("emhana6.kz",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/storage/app",),
        evidence_url="https://emhana6.kz/ru/paid",
        robots_url="https://emhana6.kz/robots.txt",
        notes="Linked storage documents are disallowed by robots.",
    ),
    _source(
        source_id="almaty_cgkb",
        display_name="ЦГКБ Алматы",
        source_type="state_clinic",
        mode=SourceMode.LIVE,
        priority="P0",
        formats=(SourceFormat.HTML, SourceFormat.PDF, SourceFormat.XLSX),
        allowed_hosts=("almaty-cgkb.kz", "www.almaty-cgkb.kz"),
        allowed_paths=("/kz/prajs-parak",),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/wp-admin",),
        start_urls=("https://almaty-cgkb.kz/kz/prajs-parak/",),
        cities=("Алматы",),
        delay=15,
        pages=5,
        evidence_url="https://almaty-cgkb.kz/kz/prajs-parak/",
        robots_url="https://almaty-cgkb.kz/robots.txt",
        notes="Linked files require exact URL approval before use.",
        enabled=True,
    ),
    _source(
        source_id="sema_hospital",
        display_name="SEMA Hospital",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("semahospital.kz", "www.semahospital.kz"),
        allowed_paths=("/price.php",),
        start_urls=("https://semahospital.kz/price.php",),
        delay=15,
        pages=20,
        evidence_url="https://semahospital.kz/",
        robots_url="https://semahospital.kz/robots.txt",
        notes="Exact current price path must be rechecked before adapter implementation.",
        enabled=True,
    ),
    _source(
        source_id="medical_park",
        display_name="Medical Park",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("medicalpark.kz",),
        allowed_paths=("/page/prices",),
        start_urls=("https://medicalpark.kz/page/prices/",),
        delay=15,
        evidence_url="https://medicalpark.kz/page/prices/",
        robots_url="https://medicalpark.kz/robots.txt",
        notes="Only registered public service and price paths are eligible.",
        enabled=True,
    ),
    _source(
        source_id="lordoctor",
        display_name="Lor Doctor",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("lordoctor.kz",),
        allowed_paths=("/price",),
        start_urls=("https://lordoctor.kz/price/",),
        delay=15,
        evidence_url="https://lordoctor.kz/price/",
        robots_url="https://lordoctor.kz/robots.txt",
        notes="Only explicit public price/service pages are eligible.",
        enabled=True,
    ),
    _source(
        source_id="sunkar_premium",
        display_name="Сункар Premium",
        source_type="private_clinic",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("sunkarpremium.kz", "www.sunkarpremium.kz"),
        evidence_url="https://sunkarpremium.kz/",
        notes="Malformed and unusual prices require source-specific validation first.",
    ),
    _source(
        source_id="onclinic_astana",
        display_name="On Clinic Astana",
        source_type="private_clinic",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("astana.onclinic.kz",),
        evidence_url="https://astana.onclinic.kz/",
        notes="Public price structure and policy remain to be confirmed.",
    ),
    _source(
        source_id="genom_eko",
        display_name="Геном ЭКО",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("genom-eko.kz",),
        allowed_paths=("/services/vrt/programmy-eko",),
        start_urls=("https://genom-eko.kz/services/vrt/programmy-eko",),
        delay=15,
        pages=5,
        evidence_url="https://genom-eko.kz/services/vrt/programmy-eko",
        robots_url="https://genom-eko.kz/robots.txt",
        notes="Recheck that the registered document is a current public price list.",
        enabled=True,
    ),
    _source(
        source_id="duet_clinic",
        display_name="Duet Clinic",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("duetclinic.kz",),
        allowed_paths=("/pricelist",),
        start_urls=("https://duetclinic.kz/pricelist/",),
        delay=15,
        evidence_url="https://duetclinic.kz/pricelist/",
        robots_url="https://duetclinic.kz/robots.txt",
        notes="Only the explicit clinic price list is eligible.",
        enabled=True,
    ),
    _source(
        source_id="mrt_lider",
        display_name="МРТ Лидер",
        source_type="diagnostics_center",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("mrt-lider.kz", "www.mrt-lider.kz"),
        evidence_url="https://mrt-lider.kz/",
        notes="City-specific price paths and policy remain unconfirmed.",
    ),
    _source(
        source_id="magnesia",
        display_name="Магнезия",
        source_type="diagnostics_center",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=(
            "magnesia.kz",
            "pavlodar.magnesia.kz",
            "semey.magnesia.kz",
            "kostanay.magnesia.kz",
        ),
        allowed_paths=("/kt", "/mrt", "/cena"),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS
        + ("/auth", "/uslug/price-list", "/upload", "/bitrix"),
        start_urls=(
            "https://pavlodar.magnesia.kz/kt/",
            "https://semey.magnesia.kz/cena/",
        ),
        delay=15,
        pages=20,
        evidence_url="https://pavlodar.magnesia.kz/kt/",
        robots_url="https://magnesia.kz/robots.txt",
        notes="City/subdomain expansion must be registered explicitly.",
        enabled=True,
    ),
    _source(
        source_id="snh",
        display_name="SNH diagnostics",
        source_type="diagnostics_center",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("snh.kz",),
        allowed_paths=(
            "/%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8-%D0%B8-%D1%86%D0%B5%D0%BD%D1%8B-%D0%BA%D1%82-%D0%B8-%D0%BC%D1%80%D1%82",
        ),
        start_urls=(
            "https://snh.kz/%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8-%D0%B8-%D1%86%D0%B5%D0%BD%D1%8B-%D0%BA%D1%82-%D0%B8-%D0%BC%D1%80%D1%82/",
        ),
        delay=15,
        evidence_url="https://snh.kz/%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8-%D0%B8-%D1%86%D0%B5%D0%BD%D1%8B-%D0%BA%D1%82-%D0%B8-%D0%BC%D1%80%D1%82/",
        robots_url="https://snh.kz/robots.txt",
        notes="Only explicit CT/MRI public price paths are eligible.",
        enabled=True,
    ),
    _source(
        source_id="tonus_med",
        display_name="Тонус-Мед",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("tonus-med.kz",),
        allowed_paths=("/ceni", "/uslugi"),
        forbidden_paths=DEFAULT_FORBIDDEN_PATHS + ("/tilda",),
        start_urls=("https://tonus-med.kz/ceni",),
        delay=15,
        pages=10,
        evidence_url="https://tonus-med.kz/ceni",
        robots_url="https://tonus-med.kz/robots.txt",
        notes="Only registered appointment, diagnostic, and procedure price pages.",
        enabled=True,
    ),
    _source(
        source_id="aktobe_mc",
        display_name="Aktobe Medical Center",
        source_type="state_clinic",
        mode=SourceMode.SCAFFOLD,
        priority="P2",
        formats=(SourceFormat.HTML, SourceFormat.PDF),
        allowed_hosts=("aktobemc.kz", "www.aktobemc.kz"),
        evidence_url="https://aktobemc.kz/",
        robots_url="https://aktobemc.kz/robots.txt",
        notes="No current public paid-price page has been confirmed.",
    ),
    _source(
        source_id="qmu_clinics",
        display_name="QMU clinics",
        source_type="state_clinic",
        mode=SourceMode.MANUAL_IMPORT_ONLY,
        priority="P1",
        formats=(SourceFormat.HTML, SourceFormat.PDF, SourceFormat.DOCX, SourceFormat.XLSX),
        allowed_hosts=("qmu.edu.kz", "www.qmu.edu.kz"),
        evidence_url="https://qmu.edu.kz/",
        notes="Only an explicitly reviewed university-clinic tariff document may be imported.",
    ),
    _source(
        source_id="gpk_hippokrat",
        display_name="Гиппократ / GPK",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("gpk.kz",),
        allowed_paths=(
            "/%D0%BF%D1%80%D0%B0%D0%B9%D1%81-%D0%BB%D0%B8%D1%81%D1%82",
        ),
        start_urls=(
            "https://gpk.kz/%D0%BF%D1%80%D0%B0%D0%B9%D1%81-%D0%BB%D0%B8%D1%81%D1%82",
        ),
        delay=15,
        evidence_url="https://gpk.kz/%D0%BF%D1%80%D0%B0%D0%B9%D1%81-%D0%BB%D0%B8%D1%81%D1%82",
        robots_url="https://gpk.kz/robots.txt",
        notes="Only explicit public clinic price pages are eligible.",
        enabled=True,
    ),
    _source(
        source_id="2gis_enrichment",
        display_name="2GIS enrichment",
        source_type="map_enrichment",
        mode=SourceMode.OFFICIAL_API_REQUIRED,
        priority="P2",
        formats=(SourceFormat.API,),
        allowed_hosts=("catalog.api.2gis.com",),
        evidence_url="https://docs.2gis.com/",
        notes="Official API only; public HTML scraping is forbidden and API access is disabled.",
    ),
    _source(
        source_id="google_places_enrichment",
        display_name="Google Places enrichment",
        source_type="map_enrichment",
        mode=SourceMode.OFFICIAL_API_REQUIRED,
        priority="P2",
        formats=(SourceFormat.API,),
        allowed_hosts=("places.googleapis.com",),
        evidence_url="https://developers.google.com/maps/documentation/places/web-service",
        notes="Official API only; public Maps HTML scraping is forbidden and API access is disabled.",
    ),
    _source(
        source_id="alataulab_kz",
        display_name="AlatauLab",
        source_type="laboratory",
        mode=SourceMode.LIVE,
        priority="P0",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("alataulab.kz", "www.alataulab.kz"),
        allowed_paths=("/ru/almaty/analyzes",),
        start_urls=("https://alataulab.kz/ru/almaty/analyzes/",),
        cities=("Алматы",),
        delay=10,
        pages=20,
        evidence_url="https://alataulab.kz/ru/almaty/analyzes/",
        robots_url="https://alataulab.kz/robots.txt",
        notes="Public HTML price list for medical analyses in Almaty.",
        enabled=True,
    ),
    _source(
        source_id="onclinic_kz",
        display_name="OnClinic",
        source_type="private_clinic",
        mode=SourceMode.LIVE,
        priority="P1",
        formats=(SourceFormat.HTML,),
        allowed_hosts=("onclinic.kz", "www.onclinic.kz"),
        allowed_paths=("/price", "/page"),
        start_urls=("https://onclinic.kz/price/",),
        cities=("Астана",),
        delay=10,
        pages=15,
        evidence_url="https://onclinic.kz/price/",
        robots_url="https://onclinic.kz/robots.txt",
        notes="Public HTML price list for OnClinic services.",
        enabled=True,
    ),
)

SOURCE_REGISTRY = SourceRegistry(SOURCE_CONFIGS)

if set(SOURCE_REGISTRY.source_ids) != EXPECTED_POLICY_SOURCE_IDS:
    missing = EXPECTED_POLICY_SOURCE_IDS.difference(SOURCE_REGISTRY.source_ids)
    extra = set(SOURCE_REGISTRY.source_ids).difference(EXPECTED_POLICY_SOURCE_IDS)
    raise RuntimeError(f"Source registry mismatch; missing={sorted(missing)}, extra={sorted(extra)}")
